namespace LockIn.Services;

public static class SwedishExerciseNames
{
    public static readonly Dictionary<string, string> Map = new(StringComparer.OrdinalIgnoreCase)
    {
        // Bröst
        ["Barbell Bench Press - Medium Grip"]          = "Bänkpress",
        ["Barbell Incline Bench Press - Medium Grip"]  = "Lutande bänkpress",
        ["Decline Barbell Bench Press"]                = "Liggande bänkpress",
        ["Cable Crossover"]                            = "Kabelkorsning",
        ["Dips - Chest Version"]                       = "Dips",
        ["Chest Dip"]                                  = "Bröstdips",
        ["Dumbbell Bench Press"]                       = "Hantel bänkpress",
        ["Incline Dumbbell Press"]                     = "Lutande hantelpress",
        ["Decline Dumbbell Bench Press"]               = "Liggande hantel bänkpress",
        ["Dumbbell Flyes"]                             = "Hantelflyes",
        ["Incline Dumbbell Flyes"]                     = "Lutande hantelflyes",
        ["Decline Dumbbell Flyes"]                     = "Liggande hantelflyes",
        ["Pec Deck Flyes"]                             = "Pec deck",
        ["Machine Chest Press"]                        = "Bröstmaskin",
        ["Smith Machine Bench Press"]                  = "Bänkpress Smithmaskin",
        ["Incline Cable Flye"]                         = "Lutande kabelflyes",
        ["Close-Grip Barbell Bench Press"]             = "Smalt grepp bänkpress",
        ["Push-Up"]                                    = "Armhävning",
        ["Wide-Grip Barbell Bench Press"]              = "Bredgrepp bänkpress",
        ["Svend Press"]                                = "Svend press",

        // Rygg
        ["Barbell Deadlift"]                           = "Marklyft",
        ["Romanian Deadlift"]                          = "Rumänska marklyft",
        ["Sumo Deadlift"]                              = "Sumomarklyft",
        ["Rack Pulls"]                                 = "Rack pull",
        ["Bent Over Barbell Row"]                      = "Skivstångsrodd",
        ["T-Bar Row"]                                  = "T-stångsrodd",
        ["Lat Pulldown"]                               = "Latsdrag",
        ["Wide-Grip Lat Pulldown"]                     = "Bredgrepp latsdrag",
        ["Close-Grip Front Lat Pulldown"]              = "Smalt grepp latsdrag",
        ["Seated Cable Rows"]                          = "Sittande rodd",
        ["Seated Cable Pulley Rows - Wide Grip"]       = "Sittande bredgrepp rodd",
        ["Pull-Up"]                                    = "Chins",
        ["Chin-Up"]                                    = "Chins underhandsfattning",
        ["One-Arm Dumbbell Row"]                       = "Hantelrodd en arm",
        ["Dumbbell Row"]                               = "Hantelrodd",
        ["Hyperextensions"]                            = "Ryggsträckning",
        ["Back Extension"]                             = "Ryggsträckning",
        ["Good Morning"]                               = "Good morning",
        ["Straight-Arm Pulldown"]                      = "Raka armars pulldown",
        ["Barbell Shrug"]                              = "Nacklyft stång",
        ["Dumbbell Shrug"]                             = "Nacklyft hantel",
        ["Pendlay Row"]                                = "Pendlay row",
        ["Inverted Row"]                               = "Inverterad rodd",
        ["Cable Row"]                                  = "Kabelrodd",
        ["Face Pull"]                                  = "Facepull",
        ["Seated Row"]                                 = "Sittande rodd maskin",

        // Axlar
        ["Barbell Shoulder Press"]                     = "Militärpress",
        ["Standing Military Press"]                    = "Stående militärpress",
        ["Seated Barbell Military Press"]              = "Sittande militärpress",
        ["Dumbbell Shoulder Press"]                    = "Hantel axelpress",
        ["Seated Dumbbell Press"]                      = "Sittande hantelpress",
        ["Arnold Dumbbell Press"]                      = "Arnoldpress",
        ["Side Lateral Raise"]                         = "Sidolyft",
        ["Dumbbell Front Raise"]                       = "Hantel frontlyft",
        ["Barbell Front Raise"]                        = "Stång frontlyft",
        ["Reverse Flyes"]                              = "Bakåtflyes",
        ["Upright Barbell Row"]                        = "Upprätt rodd",
        ["Smith Machine Shoulder Press"]               = "Axelpress Smithmaskin",
        ["Cable Front Raise"]                          = "Kabel frontlyft",
        ["Cable Lateral Raise"]                        = "Kabel sidolyft",
        ["Machine Shoulder Press"]                     = "Axelpress maskin",
        ["Seated Bent-Over Rear Delt Raise"]           = "Sittande bakre deltoidlyft",
        ["Bent Over Two-Dumbbell Row"]                 = "Böjd framåt hantelrodd",

        // Biceps
        ["Barbell Curl"]                               = "Skivstångscurl",
        ["EZ-Bar Curl"]                                = "EZ-stångscurl",
        ["Barbell Preacher Curl"]                      = "Stång preachers curl",
        ["Dumbbell Curl"]                              = "Hantelcurl",
        ["Hammer Curls"]                               = "Hammarcurl",
        ["Concentration Curls"]                        = "Koncentrationscurl",
        ["Cable Curl"]                                 = "Kabelcurl",
        ["Cable Hammer Curls - Rope Attachment"]       = "Kabel hammarcurl",
        ["Preacher Curl"]                              = "Preachers curl",
        ["Seated Dumbbell Curl"]                       = "Sittande hantelcurl",
        ["Incline Dumbbell Curl"]                      = "Lutande hantelcurl",
        ["Reverse Curl"]                               = "Omvänd curl",
        ["Close-Grip EZ-Bar Curl"]                     = "EZ-stångscurl smalt grepp",
        ["Wide-Grip Barbell Curl"]                     = "Bredgrepp skivstångscurl",
        ["Zottman Curl"]                               = "Zottman curl",
        ["Spider Curl"]                                = "Spider curl",

        // Triceps
        ["EZ-Bar Skullcrusher"]                        = "Skullcrusher",
        ["Triceps Pushdown"]                           = "Tricepspressdown",
        ["Tricep Pushdown - Rope Attachment"]          = "Tricepspressdown rep",
        ["Lying Triceps Press"]                        = "Liggande tricepspress",
        ["Overhead Triceps Extension"]                 = "Overhead tricepsext",
        ["Cable Rope Overhead Triceps Extension"]      = "Rep overhead tricepsext",
        ["Tricep Dumbbell Kickback"]                   = "Tricepskickback",
        ["Bench Dips"]                                 = "Bänkdips",
        ["Weighted Bench Dip"]                         = "Viktat bänkdips",
        ["Dip"]                                        = "Dips",
        ["Close-Grip Bench Press"]                     = "Smalt grepp bänkpress",
        ["Standing Dumbbell Triceps Extension"]        = "Stående hantel tricepsext",
        ["Skull Crusher"]                              = "Skullcrusher",
        ["Dumbbell Tricep Extension"]                  = "Hantel tricepsext",

        // Ben
        ["Barbell Squat"]                              = "Knäböj",
        ["Barbell Full Squat"]                         = "Knäböj",
        ["Front Squat"]                                = "Framknäböj",
        ["Hack Squat"]                                 = "Hackknäböj",
        ["Leg Press"]                                  = "Benpress",
        ["Barbell Lunge"]                              = "Utfall",
        ["Dumbbell Lunges"]                            = "Hantelutfall",
        ["Walking Lunge"]                              = "Gångutfall",
        ["Reverse Lunge"]                              = "Bakåtutfall",
        ["Bulgarian Split Squat"]                      = "Bulgariskt knäböj",
        ["Lying Leg Curls"]                            = "Liggande benböjning",
        ["Leg Curl"]                                   = "Benböjning",
        ["Seated Leg Curl"]                            = "Sittande benböjning",
        ["Leg Extension"]                              = "Bensträckning",
        ["Calf Press On The Leg Press Machine"]        = "Vadpress benpress",
        ["Standing Calf Raises"]                       = "Stående vadpress",
        ["Seated Calf Raise"]                          = "Sittande vadpress",
        ["Smith Machine Squat"]                        = "Knäböj Smithmaskin",
        ["Goblet Squat"]                               = "Goblet knäböj",
        ["Hip Thrust"]                                 = "Hip thrust",
        ["Glute Ham Raise"]                            = "Glute ham raise",
        ["Box Jump"]                                   = "Box jump",
        ["Dumbbell Step Ups"]                          = "Hantel stegövning",
        ["Step-Up"]                                    = "Stegövning",
        ["Sumo Squat"]                                 = "Sumoknäböj",
        ["Smith Machine Calf Raise"]                   = "Vadpress Smithmaskin",
        ["Donkey Calf Raises"]                         = "Åsnevadraise",
        ["Single Leg Calf Raise"]                      = "Ettbent vadpress",
        ["Stiff-Legged Deadlift"]                      = "Styv marklyft",
        ["Single-Leg Deadlift"]                        = "Ettbent marklyft",
        ["Trap Bar Deadlift"]                          = "Hexstångsmarklyft",
        ["Kettlebell Swing"]                           = "Kettlebellsvingning",

        // Core
        ["Plank"]                                      = "Plankan",
        ["Crunches"]                                   = "Crunches",
        ["Russian Twist"]                              = "Rysk twist",
        ["Cable Crunch"]                               = "Kabelcrunch",
        ["Hanging Leg Raise"]                          = "Hängande benlyft",
        ["Hanging Knee Raise"]                         = "Hängande knälyft",
        ["Ab Roller"]                                  = "Maghjul",
        ["Decline Crunch"]                             = "Nedåtlutad crunch",
        ["Oblique Crunches"]                           = "Sidocrunch",
        ["Sit-Up"]                                     = "Sit-up",
        ["Bicycle Crunch"]                             = "Cykelcrunch",
        ["Mountain Climbers"]                          = "Mountain climbers",
        ["Leg Raise"]                                  = "Benlyft",
        ["Side Plank"]                                 = "Sidoplankan",
        ["Decline Oblique Crunch"]                     = "Nedåtlutad sidocrunch",
        ["Reverse Crunch"]                             = "Omvänd crunch",
        ["Dragon Flag"]                                = "Dragon flag",
        ["Windmill"]                                   = "Väderkvarn",
        ["V-Up"]                                       = "V-lyft",
        ["Jackknife Sit-Up"]                           = "Knivbrett sit-up",
        ["Elbow Plank"]                                = "Armbågsplankan",
    };
}
